"""Meaning-aligned Romance Swadesh + closed class.

Full README corpus minus English (34 lects). Extremaduran kept — book source
available. Each lect has its own conjugation table in lacyo.paradigms.
"""

from __future__ import annotations

from typing import TypedDict


from lacyo.paradigms import PERSONS
from lacyo.swadesh_rest import TABLES as REST_TABLES

SOURCE_LANGS = (
    "fr", "es", "it", "pt", "ca", "ro", "gl", "oc",
    "an", "ast", "ext", "lad", "mwl",
    "scn", "vec", "lmo", "pms", "lij", "fur", "eml", "lld", "ist",
    "wa", "pcd", "nrm", "frp", "glw", "gsc",
    "la", "rm", "sc", "rup", "ruo", "dlm",
)


class Concept(TypedDict):
    id: str
    gloss_es: str
    pos: str
    fr: str
    es: str
    it: str
    pt: str
    ca: str


# (id, gloss_es, pos, fr, es, it, pt)
_ROWS: tuple[tuple[str, str, str, str, str, str, str], ...] = (
    # Swadesh 207
    ("i", "yo", "pron", "je", "yo", "io", "eu"),
    ("you_sg", "tú", "pron", "tu", "tú", "tu", "tu"),
    ("he", "él", "pron", "il", "él", "lui", "ele"),
    ("we", "nosotros", "pron", "nous", "nosotros", "noi", "nós"),
    ("you_pl", "vosotros", "pron", "vous", "vosotros", "voi", "vocês"),
    ("they", "ellos", "pron", "ils", "ellos", "loro", "eles"),
    ("this", "esto", "det", "ceci", "esto", "questo", "isto"),
    ("that", "eso", "det", "cela", "eso", "quello", "isso"),
    ("here", "aquí", "adv", "ici", "aquí", "qui", "aqui"),
    ("there", "allí", "adv", "là", "allí", "lì", "ali"),
    ("who", "quién", "pron", "qui", "quién", "chi", "quem"),
    ("what", "qué", "pron", "quoi", "qué", "che", "que"),
    ("where", "dónde", "adv", "où", "dónde", "dove", "onde"),
    ("when", "cuándo", "adv", "quand", "cuándo", "quando", "quando"),
    ("how", "cómo", "adv", "comment", "cómo", "come", "como"),
    ("not", "no", "adv", "non", "no", "non", "não"),
    ("all", "todo", "det", "tout", "todo", "tutto", "todo"),
    ("many", "muchos", "det", "beaucoup", "muchos", "molti", "muitos"),
    ("some", "algunos", "det", "quelques", "algunos", "alcuni", "alguns"),
    ("few", "pocos", "det", "peu", "pocos", "pochi", "poucos"),
    ("other", "otro", "det", "autre", "otro", "altro", "outro"),
    ("one", "uno", "num", "un", "uno", "uno", "um"),
    ("two", "dos", "num", "deux", "dos", "due", "dois"),
    ("three", "tres", "num", "trois", "tres", "tre", "três"),
    ("four", "cuatro", "num", "quatre", "cuatro", "quattro", "quatro"),
    ("five", "cinco", "num", "cinq", "cinco", "cinque", "cinco"),
    ("big", "grande", "adj", "grand", "grande", "grande", "grande"),
    ("long", "largo", "adj", "long", "largo", "lungo", "longo"),
    ("wide", "ancho", "adj", "large", "ancho", "largo", "largo"),
    ("thick", "grueso", "adj", "épais", "grueso", "spesso", "grosso"),
    ("heavy", "pesado", "adj", "lourd", "pesado", "pesante", "pesado"),
    ("small", "pequeño", "adj", "petit", "pequeño", "piccolo", "pequeno"),
    ("short", "corto", "adj", "court", "corto", "corto", "curto"),
    ("narrow", "estrecho", "adj", "étroit", "estrecho", "stretto", "estreito"),
    ("thin", "delgado", "adj", "mince", "delgado", "sottile", "fino"),
    ("woman", "mujer", "noun", "femme", "mujer", "donna", "mulher"),
    ("man", "hombre", "noun", "homme", "hombre", "uomo", "homem"),
    ("person", "persona", "noun", "personne", "persona", "persona", "pessoa"),
    ("child", "niño", "noun", "enfant", "niño", "bambino", "criança"),
    ("wife", "esposa", "noun", "épouse", "esposa", "moglie", "esposa"),
    ("husband", "esposo", "noun", "mari", "esposo", "marito", "marido"),
    ("mother", "madre", "noun", "mère", "madre", "madre", "mãe"),
    ("father", "padre", "noun", "père", "padre", "padre", "pai"),
    ("animal", "animal", "noun", "animal", "animal", "animale", "animal"),
    ("fish", "pez", "noun", "poisson", "pez", "pesce", "peixe"),
    ("bird", "pájaro", "noun", "oiseau", "pájaro", "uccello", "pássaro"),
    ("dog", "perro", "noun", "chien", "perro", "cane", "cão"),
    ("louse", "piojo", "noun", "pou", "piojo", "pidocchio", "piolho"),
    ("snake", "serpiente", "noun", "serpent", "serpiente", "serpente", "serpente"),
    ("worm", "gusano", "noun", "ver", "gusano", "verme", "verme"),
    ("tree", "árbol", "noun", "arbre", "árbol", "albero", "árvore"),
    ("forest", "bosque", "noun", "forêt", "bosque", "foresta", "floresta"),
    ("stick", "palo", "noun", "bâton", "palo", "bastone", "pau"),
    ("fruit", "fruta", "noun", "fruit", "fruta", "frutto", "fruta"),
    ("seed", "semilla", "noun", "graine", "semilla", "seme", "semente"),
    ("leaf", "hoja", "noun", "feuille", "hoja", "foglia", "folha"),
    ("root", "raíz", "noun", "racine", "raíz", "radice", "raiz"),
    ("bark", "corteza", "noun", "écorce", "corteza", "corteccia", "casca"),
    ("flower", "flor", "noun", "fleur", "flor", "fiore", "flor"),
    ("grass", "hierba", "noun", "herbe", "hierba", "erba", "erva"),
    ("rope", "cuerda", "noun", "corde", "cuerda", "corda", "corda"),
    ("skin", "piel", "noun", "peau", "piel", "pelle", "pele"),
    ("meat", "carne", "noun", "viande", "carne", "carne", "carne"),
    ("blood", "sangre", "noun", "sang", "sangre", "sangue", "sangue"),
    ("bone", "hueso", "noun", "os", "hueso", "osso", "osso"),
    ("fat", "grasa", "noun", "graisse", "grasa", "grasso", "gordura"),
    ("egg", "huevo", "noun", "œuf", "huevo", "uovo", "ovo"),
    ("horn", "cuerno", "noun", "corne", "cuerno", "corno", "chifre"),
    ("tail", "cola", "noun", "queue", "cola", "coda", "rabo"),
    ("feather", "pluma", "noun", "plume", "pluma", "piuma", "pena"),
    ("hair", "pelo", "noun", "cheveu", "pelo", "capello", "cabelo"),
    ("head", "cabeza", "noun", "tête", "cabeza", "testa", "cabeça"),
    ("ear", "oreja", "noun", "oreille", "oreja", "orecchio", "orelha"),
    ("eye", "ojo", "noun", "œil", "ojo", "occhio", "olho"),
    ("nose", "nariz", "noun", "nez", "nariz", "naso", "nariz"),
    ("mouth", "boca", "noun", "bouche", "boca", "bocca", "boca"),
    ("tooth", "diente", "noun", "dent", "diente", "dente", "dente"),
    ("tongue", "lengua", "noun", "langue", "lengua", "lingua", "língua"),
    ("fingernail", "uña", "noun", "ongle", "uña", "unghia", "unha"),
    ("foot", "pie", "noun", "pied", "pie", "piede", "pé"),
    ("leg", "pierna", "noun", "jambe", "pierna", "gamba", "perna"),
    ("knee", "rodilla", "noun", "genou", "rodilla", "ginocchio", "joelho"),
    ("hand", "mano", "noun", "main", "mano", "mano", "mão"),
    ("wing", "ala", "noun", "aile", "ala", "ala", "asa"),
    ("belly", "vientre", "noun", "ventre", "vientre", "pancia", "ventre"),
    ("guts", "entrañas", "noun", "entrailles", "entrañas", "viscere", "tripas"),
    ("neck", "cuello", "noun", "cou", "cuello", "collo", "pescoço"),
    ("back", "espalda", "noun", "dos", "espalda", "schiena", "costas"),
    ("breast", "pecho", "noun", "sein", "pecho", "petto", "peito"),
    ("heart", "corazón", "noun", "cœur", "corazón", "cuore", "coração"),
    ("liver", "hígado", "noun", "foie", "hígado", "fegato", "fígado"),
    ("drink", "beber", "verb", "boire", "beber", "bere", "beber"),
    ("eat", "comer", "verb", "manger", "comer", "mangiare", "comer"),
    ("bite", "morder", "verb", "mordre", "morder", "mordere", "morder"),
    ("suck", "chupar", "verb", "sucer", "chupar", "succhiare", "chupar"),
    ("spit", "escupir", "verb", "cracher", "escupir", "sputare", "cuspir"),
    ("vomit", "vomitar", "verb", "vomir", "vomitar", "vomitare", "vomitar"),
    ("blow", "soplar", "verb", "souffler", "soplar", "soffiare", "soprar"),
    ("breathe", "respirar", "verb", "respirer", "respirar", "respirare", "respirar"),
    ("laugh", "reír", "verb", "rire", "reír", "ridere", "rir"),
    ("see", "ver", "verb", "voir", "ver", "vedere", "ver"),
    ("hear", "oír", "verb", "entendre", "oír", "sentire", "ouvir"),
    ("know", "saber", "verb", "savoir", "saber", "sapere", "saber"),
    ("think", "pensar", "verb", "penser", "pensar", "pensare", "pensar"),
    ("smell", "oler", "verb", "sentir", "oler", "odorare", "cheirar"),
    ("fear", "temer", "verb", "craindre", "temer", "temere", "temer"),
    ("sleep", "dormir", "verb", "dormir", "dormir", "dormire", "dormir"),
    ("live", "vivir", "verb", "vivre", "vivir", "vivere", "viver"),
    ("die", "morir", "verb", "mourir", "morir", "morire", "morrer"),
    ("kill", "matar", "verb", "tuer", "matar", "uccidere", "matar"),
    ("fight", "pelear", "verb", "combattre", "pelear", "combattere", "lutar"),
    ("hunt", "cazar", "verb", "chasser", "cazar", "cacciare", "caçar"),
    ("hit", "golpear", "verb", "frapper", "golpear", "colpire", "bater"),
    ("cut", "cortar", "verb", "couper", "cortar", "tagliare", "cortar"),
    ("split", "partir", "verb", "fendre", "partir", "spaccare", "fender"),
    ("stab", "apuñalar", "verb", "poignarder", "apuñalar", "pugnalare", "esfaquear"),
    ("scratch", "rascar", "verb", "gratter", "rascar", "grattare", "coçar"),
    ("dig", "cavar", "verb", "creuser", "cavar", "scavare", "cavar"),
    ("swim", "nadar", "verb", "nager", "nadar", "nuotare", "nadar"),
    ("fly", "volar", "verb", "voler", "volar", "volare", "voar"),
    ("walk", "caminar", "verb", "marcher", "caminar", "camminare", "andar"),
    ("come", "venir", "verb", "venir", "venir", "venire", "vir"),
    ("lie", "yacer", "verb", "gésir", "yacer", "giacere", "jazer"),
    ("sit", "sentar", "verb", "asseoir", "sentar", "sedere", "sentar"),
    ("stand", "parar", "verb", "tenir", "parar", "stare", "ficar"),
    ("turn", "girar", "verb", "tourner", "girar", "girare", "girar"),
    ("fall", "caer", "verb", "tomber", "caer", "cadere", "cair"),
    ("give", "dar", "verb", "donner", "dar", "dare", "dar"),
    ("hold", "tener", "verb", "tenir", "tener", "tenere", "ter"),
    ("squeeze", "apretar", "verb", "presser", "apretar", "spremere", "apertar"),
    ("rub", "frotar", "verb", "frotter", "frotar", "strofinare", "esfregar"),
    ("wash", "lavar", "verb", "laver", "lavar", "lavare", "lavar"),
    ("wipe", "secar", "verb", "essuyer", "secar", "asciugare", "enxugar"),
    ("pull", "tirar", "verb", "tirer", "tirar", "tirare", "puxar"),
    ("push", "empujar", "verb", "pousser", "empujar", "spingere", "empurrar"),
    ("throw", "lanzar", "verb", "jeter", "lanzar", "lanciare", "atirar"),
    ("tie", "atar", "verb", "lier", "atar", "legare", "atar"),
    ("sew", "coser", "verb", "coudre", "coser", "cucire", "costurar"),
    ("count", "contar", "verb", "compter", "contar", "contare", "contar"),
    ("say", "decir", "verb", "dire", "decir", "dire", "dizer"),
    ("sing", "cantar", "verb", "chanter", "cantar", "cantare", "cantar"),
    ("play", "jugar", "verb", "jouer", "jugar", "giocare", "jogar"),
    ("float", "flotar", "verb", "flotter", "flotar", "galleggiare", "flutuar"),
    ("flow", "fluir", "verb", "couler", "fluir", "fluire", "fluir"),
    ("freeze", "congelar", "verb", "geler", "congelar", "gelare", "congelar"),
    ("swell", "hinchar", "verb", "enfler", "hinchar", "gonfiare", "inchar"),
    ("sun", "sol", "noun", "soleil", "sol", "sole", "sol"),
    ("moon", "luna", "noun", "lune", "luna", "luna", "lua"),
    ("star", "estrella", "noun", "étoile", "estrella", "stella", "estrela"),
    ("water", "agua", "noun", "eau", "agua", "acqua", "água"),
    ("rain", "lluvia", "noun", "pluie", "lluvia", "pioggia", "chuva"),
    ("river", "río", "noun", "rivière", "río", "fiume", "rio"),
    ("lake", "lago", "noun", "lac", "lago", "lago", "lago"),
    ("sea", "mar", "noun", "mer", "mar", "mare", "mar"),
    ("salt", "sal", "noun", "sel", "sal", "sale", "sal"),
    ("stone", "piedra", "noun", "pierre", "piedra", "pietra", "pedra"),
    ("sand", "arena", "noun", "sable", "arena", "sabbia", "areia"),
    ("dust", "polvo", "noun", "poussière", "polvo", "polvere", "pó"),
    ("earth", "tierra", "noun", "terre", "tierra", "terra", "terra"),
    ("cloud", "nube", "noun", "nuage", "nube", "nuvola", "nuvem"),
    ("fog", "niebla", "noun", "brouillard", "niebla", "nebbia", "nevoeiro"),
    ("sky", "cielo", "noun", "ciel", "cielo", "cielo", "céu"),
    ("wind", "viento", "noun", "vent", "viento", "vento", "vento"),
    ("snow", "nieve", "noun", "neige", "nieve", "neve", "neve"),
    ("ice", "hielo", "noun", "glace", "hielo", "ghiaccio", "gelo"),
    ("smoke", "humo", "noun", "fumée", "humo", "fumo", "fumo"),
    ("fire", "fuego", "noun", "feu", "fuego", "fuoco", "fogo"),
    ("ash", "ceniza", "noun", "cendre", "ceniza", "cenere", "cinza"),
    ("burn", "quemar", "verb", "brûler", "quemar", "bruciare", "queimar"),
    ("road", "camino", "noun", "route", "camino", "strada", "estrada"),
    ("mountain", "montaña", "noun", "montagne", "montaña", "montagna", "montanha"),
    ("red", "rojo", "adj", "rouge", "rojo", "rosso", "vermelho"),
    ("green", "verde", "adj", "vert", "verde", "verde", "verde"),
    ("yellow", "amarillo", "adj", "jaune", "amarillo", "giallo", "amarelo"),
    ("white", "blanco", "adj", "blanc", "blanco", "bianco", "branco"),
    ("black", "negro", "adj", "noir", "negro", "nero", "preto"),
    ("night", "noche", "noun", "nuit", "noche", "notte", "noite"),
    ("day", "día", "noun", "jour", "día", "giorno", "dia"),
    ("year", "año", "noun", "année", "año", "anno", "ano"),
    ("warm", "caliente", "adj", "chaud", "caliente", "caldo", "quente"),
    ("cold", "frío", "adj", "froid", "frío", "freddo", "frio"),
    ("full", "lleno", "adj", "plein", "lleno", "pieno", "cheio"),
    ("new", "nuevo", "adj", "nouveau", "nuevo", "nuovo", "novo"),
    ("old", "viejo", "adj", "vieux", "viejo", "vecchio", "velho"),
    ("good", "bueno", "adj", "bon", "bueno", "buono", "bom"),
    ("bad", "malo", "adj", "mauvais", "malo", "cattivo", "mau"),
    ("rotten", "podrido", "adj", "pourri", "podrido", "marcio", "podre"),
    ("dirty", "sucio", "adj", "sale", "sucio", "sporco", "sujo"),
    ("straight", "recto", "adj", "droit", "recto", "dritto", "direito"),
    ("round", "redondo", "adj", "rond", "redondo", "rotondo", "redondo"),
    ("sharp", "afilado", "adj", "aigu", "afilado", "affilato", "afiado"),
    ("dull", "romo", "adj", "émoussé", "romo", "smussato", "cego"),
    ("smooth", "liso", "adj", "lisse", "liso", "liscio", "liso"),
    ("wet", "mojado", "adj", "mouillé", "mojado", "bagnato", "molhado"),
    ("dry", "seco", "adj", "sec", "seco", "secco", "seco"),
    ("correct", "correcto", "adj", "correct", "correcto", "corretto", "correto"),
    ("near", "cerca", "adv", "près", "cerca", "vicino", "perto"),
    ("far", "lejos", "adv", "loin", "lejos", "lontano", "longe"),
    ("right", "derecha", "noun", "droite", "derecha", "destra", "direita"),
    ("left", "izquierda", "noun", "gauche", "izquierda", "sinistra", "esquerda"),
    ("at", "a", "adp", "à", "a", "a", "a"),
    ("in", "en", "adp", "dans", "en", "in", "em"),
    ("with", "con", "adp", "avec", "con", "con", "com"),
    ("and", "y", "conj", "et", "y", "e", "e"),
    ("if", "si", "conj", "si", "si", "se", "se"),
    ("because", "porque", "conj", "parce", "porque", "perché", "porque"),
    ("name", "nombre", "noun", "nom", "nombre", "nome", "nome"),
    # Closed class + pitch extras (sentence demos)
    ("def_art", "el", "det", "le", "el", "il", "o"),
    ("copula", "ser", "verb", "être", "ser", "essere", "ser"),
    ("cat", "gato", "noun", "chat", "gato", "gatto", "gato"),
    ("cat_f", "gata", "noun", "chatte", "gata", "gatta", "gata"),
    ("dog_f", "perra", "noun", "chienne", "perra", "cagna", "cadela"),
    ("smile", "sonreír", "verb", "sourire", "sonreír", "sorridere", "sorrir"),
)


# Catalan citation forms, aligned by concept id. Attested only — gat is Catalan, not clipped gato.
_CA: dict[str, str] = {
    "i": "jo", "you_sg": "tu", "he": "ell", "we": "nosaltres",
    "you_pl": "vosaltres", "they": "ells",
    "this": "aquest", "that": "aquell", "here": "aquí", "there": "allà",
    "who": "qui", "what": "què", "where": "on", "when": "quan", "how": "com",
    "not": "no", "all": "tot", "many": "molts", "some": "alguns", "few": "pocs",
    "other": "altre", "one": "un", "two": "dos", "three": "tres", "four": "quatre",
    "five": "cinc", "big": "gran", "long": "llarg", "wide": "ample", "thick": "gruixut",
    "heavy": "pesat", "small": "petit", "short": "curt", "narrow": "estret", "thin": "prim",
    "woman": "dona", "man": "home", "person": "persona", "child": "nen",
    "wife": "muller", "husband": "marit", "mother": "mare", "father": "pare",
    "animal": "animal", "fish": "peix", "bird": "ocell", "dog": "gos", "louse": "poll",
    "snake": "serp", "worm": "cuc", "tree": "arbre", "forest": "bosc", "stick": "pal",
    "fruit": "fruita", "seed": "llavor", "leaf": "fulla", "root": "arrel", "bark": "escorça",
    "flower": "flor", "grass": "herba", "rope": "corda", "skin": "pell", "meat": "carn",
    "blood": "sang", "bone": "os", "fat": "greix", "egg": "ou", "horn": "banya",
    "tail": "cua", "feather": "ploma", "hair": "cabell", "head": "cap", "ear": "orella",
    "eye": "ull", "nose": "nas", "mouth": "boca", "tooth": "dent", "tongue": "llengua",
    "fingernail": "ungla", "foot": "peu", "leg": "cama", "knee": "genoll", "hand": "mà",
    "wing": "ala", "belly": "ventre", "guts": "budells", "neck": "coll", "back": "esquena",
    "breast": "pit", "heart": "cor", "liver": "fetge",
    "drink": "beure", "eat": "menjar", "bite": "mossegar", "suck": "xuclar", "spit": "escopir",
    "vomit": "vomitar", "blow": "bufar", "breathe": "respirar", "laugh": "riure",
    "see": "veure", "hear": "sentir", "know": "saber", "think": "pensar", "smell": "ensumar",
    "fear": "témer", "sleep": "dormir", "live": "viure", "die": "morir", "kill": "matar",
    "fight": "lluitar", "hunt": "caçar", "hit": "pegar", "cut": "tallar", "split": "fendre",
    "stab": "apunyalar", "scratch": "gratar", "dig": "cavar", "swim": "nedar", "fly": "volar",
    "walk": "caminar", "come": "venir", "lie": "jeure", "sit": "seure", "stand": "estar",
    "turn": "girar", "fall": "caure", "give": "donar", "hold": "tenir", "squeeze": "prémer",
    "rub": "fregar", "wash": "rentar", "wipe": "eixugar", "pull": "estirar", "push": "empènyer",
    "throw": "llançar", "tie": "lligar", "sew": "cosir", "count": "comptar", "say": "dir",
    "sing": "cantar", "play": "jugar", "float": "flotar", "flow": "fluir", "freeze": "gelar",
    "swell": "inflar",
    "sun": "sol", "moon": "lluna", "star": "estrella", "water": "aigua", "rain": "pluja",
    "river": "riu", "lake": "llac", "sea": "mar", "salt": "sal", "stone": "pedra",
    "sand": "sorra", "dust": "pols", "earth": "terra", "cloud": "núvol", "fog": "boira",
    "sky": "cel", "wind": "vent", "snow": "neu", "ice": "gel", "smoke": "fum",
    "fire": "foc", "ash": "cendra", "burn": "cremar", "road": "camí", "mountain": "muntanya",
    "red": "roig", "green": "verd", "yellow": "groc", "white": "blanc", "black": "negre",
    "night": "nit", "day": "dia", "year": "any", "warm": "calent", "cold": "fred",
    "full": "ple", "new": "nou", "old": "vell", "good": "bo", "bad": "dolent",
    "rotten": "podrit", "dirty": "brut", "straight": "recte", "round": "rodó",
    "sharp": "esmolat", "dull": "rom", "smooth": "llis", "wet": "mullat", "dry": "sec",
    "correct": "correcte", "near": "prop", "far": "lluny", "right": "dreta", "left": "esquerra",
    "at": "a", "in": "en", "with": "amb", "and": "i", "if": "si", "because": "perquè",
    "name": "nom",
    "def_art": "el", "copula": "ser", "cat": "gat", "cat_f": "gata",
    "dog_f": "gossa", "smile": "somriure",
}

_RO: dict[str, str] = {
    "i": "eu", "you_sg": "tu", "he": "el", "we": "noi",
    "you_pl": "voi", "they": "ei",
    "this": "acesta", "that": "acela", "here": "aici", "there": "acolo",
    "who": "cine", "what": "ce", "where": "unde", "when": "când", "how": "cum",
    "not": "nu", "all": "tot", "many": "mulți", "some": "unii", "few": "puțini",
    "other": "alt", "one": "unu", "two": "doi", "three": "trei", "four": "patru",
    "five": "cinci", "big": "mare", "long": "lung", "wide": "lat", "thick": "gros",
    "heavy": "greu", "small": "mic", "short": "scurt", "narrow": "îngust", "thin": "subțire",
    "woman": "femeie", "man": "bărbat", "person": "persoană", "child": "copil",
    "wife": "soție", "husband": "soț", "mother": "mamă", "father": "tată",
    "animal": "animal", "fish": "pește", "bird": "pasăre", "dog": "câine", "louse": "păduche",
    "snake": "șarpe", "worm": "vierme", "tree": "copac", "forest": "pădure", "stick": "băț",
    "fruit": "fruct", "seed": "sămânță", "leaf": "frunză", "root": "rădăcină", "bark": "scoarță",
    "flower": "floare", "grass": "iarbă", "rope": "frânghie", "skin": "piele", "meat": "carne",
    "blood": "sânge", "bone": "os", "fat": "grăsime", "egg": "ou", "horn": "corn",
    "tail": "coadă", "feather": "pană", "hair": "păr", "head": "cap", "ear": "ureche",
    "eye": "ochi", "nose": "nas", "mouth": "gură", "tooth": "dinte", "tongue": "limbă",
    "fingernail": "unghie", "foot": "picior", "leg": "picior", "knee": "genunchi", "hand": "mână",
    "wing": "aripă", "belly": "burtă", "guts": "măruntaie", "neck": "gât", "back": "spate",
    "breast": "sân", "heart": "inimă", "liver": "ficat",
    "drink": "bea", "eat": "mânca", "bite": "mușca", "suck": "suge", "spit": "scuipa",
    "vomit": "vomita", "blow": "sufla", "breathe": "respira", "laugh": "râde",
    "see": "vedea", "hear": "auzi", "know": "ști", "think": "gândi", "smell": "mirosi",
    "fear": "teme", "sleep": "dormi", "live": "trăi", "die": "muri", "kill": "ucide",
    "fight": "lupta", "hunt": "vâna", "hit": "lovi", "cut": "tăia", "split": "despica",
    "stab": "înjunghia", "scratch": "zgâria", "dig": "săpa", "swim": "înota", "fly": "zbura",
    "walk": "umbla", "come": "veni", "lie": "zăcea", "sit": "ședea", "stand": "sta",
    "turn": "întoarce", "fall": "cădea", "give": "da", "hold": "ține", "squeeze": "strânge",
    "rub": "freca", "wash": "spăla", "wipe": "șterge", "pull": "trage", "push": "împinge",
    "throw": "arunca", "tie": "lega", "sew": "coase", "count": "număra", "say": "zice",
    "sing": "cânta", "play": "juca", "float": "pluti", "flow": "curge", "freeze": "îngheța",
    "swell": "umfla",
    "sun": "soare", "moon": "lună", "star": "stea", "water": "apă", "rain": "ploaie",
    "river": "râu", "lake": "lac", "sea": "mare", "salt": "sare", "stone": "piatră",
    "sand": "nisip", "dust": "praf", "earth": "pământ", "cloud": "nor", "fog": "ceață",
    "sky": "cer", "wind": "vânt", "snow": "zăpadă", "ice": "gheață", "smoke": "fum",
    "fire": "foc", "ash": "cenușă", "burn": "arde", "road": "drum", "mountain": "munte",
    "red": "roșu", "green": "verde", "yellow": "galben", "white": "alb", "black": "negru",
    "night": "noapte", "day": "zi", "year": "an", "warm": "cald", "cold": "rece",
    "full": "plin", "new": "nou", "old": "vechi", "good": "bun", "bad": "rău",
    "rotten": "putred", "dirty": "murdar", "straight": "drept", "round": "rotund",
    "sharp": "ascuțit", "dull": "tocit", "smooth": "neted", "wet": "ud", "dry": "uscat",
    "correct": "corect", "near": "aproape", "far": "departe", "right": "dreapta", "left": "stânga",
    "at": "la", "in": "în", "with": "cu", "and": "și", "if": "dacă", "because": "pentru",
    "name": "nume",
    "def_art": "cel", "copula": "fi", "cat": "pisică", "cat_f": "pisică",
    "dog_f": "cățea", "smile": "zâmbi",
}

_GL: dict[str, str] = {
    "i": "eu", "you_sg": "tu", "he": "el", "we": "nós",
    "you_pl": "vós", "they": "eles",
    "this": "isto", "that": "iso", "here": "aquí", "there": "alí",
    "who": "quen", "what": "que", "where": "onde", "when": "cando", "how": "como",
    "not": "non", "all": "todo", "many": "moitos", "some": "algúns", "few": "poucos",
    "other": "outro", "one": "un", "two": "dous", "three": "tres", "four": "catro",
    "five": "cinco", "big": "grande", "long": "longo", "wide": "ancho", "thick": "groso",
    "heavy": "pesado", "small": "pequeno", "short": "curto", "narrow": "estreito", "thin": "fino",
    "woman": "muller", "man": "home", "person": "persoa", "child": "neno",
    "wife": "esposa", "husband": "esposo", "mother": "nai", "father": "pai",
    "animal": "animal", "fish": "peixe", "bird": "paxaro", "dog": "can", "louse": "piocho",
    "snake": "serpe", "worm": "verme", "tree": "árbore", "forest": "bosque", "stick": "pau",
    "fruit": "froita", "seed": "semente", "leaf": "folla", "root": "raíz", "bark": "casca",
    "flower": "flor", "grass": "herba", "rope": "corda", "skin": "pel", "meat": "carne",
    "blood": "sangue", "bone": "oso", "fat": "graxa", "egg": "ovo", "horn": "corno",
    "tail": "rabo", "feather": "pluma", "hair": "cabelo", "head": "cabeza", "ear": "orella",
    "eye": "ollo", "nose": "nariz", "mouth": "boca", "tooth": "dente", "tongue": "lingua",
    "fingernail": "uña", "foot": "pé", "leg": "perna", "knee": "xeonllo", "hand": "man",
    "wing": "á", "belly": "ventre", "guts": "tripas", "neck": "pescozo", "back": "costas",
    "breast": "peito", "heart": "corazón", "liver": "fígado",
    "drink": "beber", "eat": "comer", "bite": "morder", "suck": "chuchar", "spit": "cuspir",
    "vomit": "vomitar", "blow": "soprar", "breathe": "respirar", "laugh": "rir",
    "see": "ver", "hear": "oír", "know": "saber", "think": "pensar", "smell": "cheirar",
    "fear": "temer", "sleep": "durmir", "live": "vivir", "die": "morrer", "kill": "matar",
    "fight": "loitar", "hunt": "cazar", "hit": "golpear", "cut": "cortar", "split": "fender",
    "stab": "apuñalar", "scratch": "rascar", "dig": "cavar", "swim": "nadar", "fly": "voar",
    "walk": "andar", "come": "vir", "lie": "xacer", "sit": "sentar", "stand": "estar",
    "turn": "xirar", "fall": "caer", "give": "dar", "hold": "ter", "squeeze": "apertar",
    "rub": "fregar", "wash": "lavar", "wipe": "enxugar", "pull": "puxar", "push": "empurrar",
    "throw": "lanzar", "tie": "atar", "sew": "coser", "count": "contar", "say": "dicir",
    "sing": "cantar", "play": "xogar", "float": "flutuar", "flow": "fluír", "freeze": "conxelar",
    "swell": "inchar",
    "sun": "sol", "moon": "lúa", "star": "estrela", "water": "auga", "rain": "choiva",
    "river": "río", "lake": "lago", "sea": "mar", "salt": "sal", "stone": "pedra",
    "sand": "area", "dust": "po", "earth": "terra", "cloud": "nube", "fog": "néboa",
    "sky": "ceo", "wind": "vento", "snow": "neve", "ice": "xeo", "smoke": "fume",
    "fire": "lume", "ash": "cinza", "burn": "queimar", "road": "camiño", "mountain": "montaña",
    "red": "vermello", "green": "verde", "yellow": "amarelo", "white": "branco", "black": "negro",
    "night": "noite", "day": "día", "year": "ano", "warm": "quente", "cold": "frío",
    "full": "cheo", "new": "novo", "old": "vello", "good": "bo", "bad": "malo",
    "rotten": "podre", "dirty": "sucio", "straight": "recto", "round": "redondo",
    "sharp": "afiado", "dull": "romo", "smooth": "liso", "wet": "mollado", "dry": "seco",
    "correct": "correcto", "near": "preto", "far": "lonxe", "right": "dereita", "left": "esquerda",
    "at": "a", "in": "en", "with": "con", "and": "e", "if": "se", "because": "porque",
    "name": "nome",
    "def_art": "o", "copula": "ser", "cat": "gato", "cat_f": "gata",
    "dog_f": "cadela", "smile": "sorrir",
}

_OC: dict[str, str] = {
    "i": "ieu", "you_sg": "tu", "he": "el", "we": "nosautres",
    "you_pl": "vosautres", "they": "eles",
    "this": "aicò", "that": "aquò", "here": "aicí", "there": "ailà",
    "who": "qual", "what": "qué", "where": "ont", "when": "quand", "how": "cossí",
    "not": "non", "all": "tot", "many": "fòrça", "some": "qualques", "few": "pauc",
    "other": "autre", "one": "un", "two": "dos", "three": "tres", "four": "quatre",
    "five": "cinc", "big": "grand", "long": "long", "wide": "larg", "thick": "espés",
    "heavy": "pesuc", "small": "pichon", "short": "cort", "narrow": "estrech", "thin": "prim",
    "woman": "femna", "man": "òme", "person": "persona", "child": "enfant",
    "wife": "esposa", "husband": "marit", "mother": "maire", "father": "paire",
    "animal": "animal", "fish": "peis", "bird": "aucèl", "dog": "can", "louse": "piolh",
    "snake": "sèrp", "worm": "vèrm", "tree": "arbre", "forest": "bòsc", "stick": "baston",
    "fruit": "fruch", "seed": "gran", "leaf": "fuèlha", "root": "raiç", "bark": "escòrça",
    "flower": "flor", "grass": "èrba", "rope": "còrda", "skin": "pèl", "meat": "carn",
    "blood": "sang", "bone": "òs", "fat": "grèis", "egg": "uòu", "horn": "còrn",
    "tail": "coa", "feather": "pluma", "hair": "pèl", "head": "cap", "ear": "aurelha",
    "eye": "uèlh", "nose": "nas", "mouth": "boca", "tooth": "dent", "tongue": "lenga",
    "fingernail": "ongla", "foot": "pè", "leg": "camba", "knee": "genolh", "hand": "man",
    "wing": "ala", "belly": "ventre", "guts": "tripas", "neck": "còl", "back": "esquina",
    "breast": "pitre", "heart": "còr", "liver": "fetge",
    "drink": "beure", "eat": "manjar", "bite": "mossegar", "suck": "suciar", "spit": "escopir",
    "vomit": "vomir", "blow": "bufar", "breathe": "respirar", "laugh": "rire",
    "see": "veire", "hear": "ausir", "know": "saber", "think": "pensar", "smell": "sentir",
    "fear": "témer", "sleep": "dormir", "live": "viure", "die": "morir", "kill": "tuar",
    "fight": "luchar", "hunt": "caçar", "hit": "tustar", "cut": "talhar", "split": "fendre",
    "stab": "apunhalar", "scratch": "gratar", "dig": "cavar", "swim": "nadar", "fly": "volar",
    "walk": "caminar", "come": "venir", "lie": "jàser", "sit": "sèire", "stand": "estar",
    "turn": "virar", "fall": "càser", "give": "donar", "hold": "tenir", "squeeze": "prémer",
    "rub": "fregar", "wash": "lavar", "wipe": "eissugar", "pull": "tirar", "push": "empénher",
    "throw": "lançar", "tie": "ligar", "sew": "cóser", "count": "comptar", "say": "dire",
    "sing": "cantar", "play": "jogar", "float": "flotar", "flow": "fluir", "freeze": "gelar",
    "swell": "enflar",
    "sun": "solelh", "moon": "luna", "star": "estela", "water": "aiga", "rain": "pluèja",
    "river": "riu", "lake": "lac", "sea": "mar", "salt": "sal", "stone": "pèira",
    "sand": "sabla", "dust": "polvera", "earth": "tèrra", "cloud": "nivol", "fog": "bruma",
    "sky": "cèl", "wind": "vent", "snow": "nèu", "ice": "glaç", "smoke": "fum",
    "fire": "fuòc", "ash": "cendre", "burn": "cremar", "road": "camin", "mountain": "montanha",
    "red": "roge", "green": "verd", "yellow": "jaune", "white": "blanc", "black": "negre",
    "night": "nuèch", "day": "jorn", "year": "an", "warm": "caud", "cold": "freg",
    "full": "plen", "new": "nòu", "old": "vièlh", "good": "bon", "bad": "marrit",
    "rotten": "porrit", "dirty": "salop", "straight": "drech", "round": "redond",
    "sharp": "agut", "dull": "emós", "smooth": "lis", "wet": "molhat", "dry": "sec",
    "correct": "correcte", "near": "prèp", "far": "luènh", "right": "drecha", "left": "esquèrra",
    "at": "a", "in": "en", "with": "amb", "and": "e", "if": "se", "because": "perque",
    "name": "nom",
    "def_art": "lo", "copula": "èsser", "cat": "gat", "cat_f": "gata",
    "dog_f": "canha", "smile": "somrire",
}

_EXTRA = {"ro": _RO, "gl": _GL, "oc": _OC}

# Masculine/feminine stem pairs. Nouns may mix sources across the pair
# (gat [ca] / chatte [fr]). Verbs are never split this way.
GENDER_PAIRS: tuple[tuple[str, str], ...] = (
    ("cat", "cat_f"),
    ("dog", "dog_f"),
)


def _validate() -> None:
    missing_conj = [L for L in SOURCE_LANGS if L not in PERSONS]
    if missing_conj:
        raise ValueError(f"lects without conjugation tables: {missing_conj}")
    ids = [row[0] for row in _ROWS]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate concept ids in Swadesh gold list")
    for name, table in (("ca", _CA), *[(k, v) for k, v in {**_EXTRA, **REST_TABLES}.items()]):
        extra = set(table) - set(ids)
        missing = set(ids) - set(table)
        if extra or missing:
            raise ValueError(f"{name} map mismatch extra={extra} missing={missing}")
    known = set(ids)
    for sent in SENTENCES:
        missing = [t for t in sent["tokens"] if t not in known]  # type: ignore[index]
        if missing:
            raise ValueError(f"sentence {sent['id']} missing concepts: {missing}")


def concepts() -> list[Concept]:
    out: list[Concept] = []
    seen: set[str] = set()
    for cid, gloss_es, pos, fr, es, it, pt in _ROWS:
        if cid in seen:
            raise ValueError(f"duplicate concept id: {cid}")
        seen.add(cid)
        if cid not in _CA:
            raise ValueError(f"missing Catalan form for {cid}")
        row: Concept = {
            "id": cid,
            "gloss_es": gloss_es,
            "pos": pos,
            "fr": fr,
            "es": es,
            "it": it,
            "pt": pt,
            "ca": _CA[cid],
        }
        for lang, table in {**_EXTRA, **REST_TABLES}.items():
            if cid not in table:
                raise ValueError(f"missing {lang} form for {cid}")
            row[lang] = table[cid]  # type: ignore[literal-required]
        out.append(row)
    return out


# Sentence demos: concept-id sequences. Authored against Spanish/Portuguese.
# Function words included so the interlinear matches the project pitch.
SENTENCES: tuple[dict[str, object], ...] = (
    {
        "id": "red_cat_smiles",
        "es": "El gato rojo sonríe.",
        "pt": "O gato vermelho sorri.",
        "tokens": ["def_art", "cat", "red", "smile"],
    },
    {
        "id": "dog_is_big",
        "es": "El perro es grande.",
        "pt": "O cão é grande.",
        "tokens": ["def_art", "dog", "copula", "big"],
    },
    {
        "id": "water_is_cold",
        "es": "El agua es fría.",
        "pt": "A água é fria.",
        "tokens": ["def_art", "water", "copula", "cold"],
    },
    {
        "id": "i_see_sun",
        "es": "Yo veo el sol.",
        "pt": "Eu vejo o sol.",
        "tokens": ["i", "see", "def_art", "sun"],
    },
    {
        "id": "woman_eats_fish",
        "es": "La mujer come pez.",
        "pt": "A mulher come peixe.",
        "tokens": ["def_art", "woman", "eat", "fish"],
    },
    {
        "id": "fire_is_red",
        "es": "El fuego es rojo.",
        "pt": "O fogo é vermelho.",
        "tokens": ["def_art", "fire", "copula", "red"],
    },
    {
        "id": "we_give_water",
        "es": "Nosotros damos agua.",
        "pt": "Nós damos água.",
        "tokens": ["we", "give", "water"],
    },
    {
        "id": "man_is_good",
        "es": "El hombre es bueno.",
        "pt": "O homem é bom.",
        "tokens": ["def_art", "man", "copula", "good"],
    },
    {
        "id": "night_is_black",
        "es": "La noche es negra.",
        "pt": "A noite é preta.",
        "tokens": ["def_art", "night", "copula", "black"],
    },
    {
        "id": "you_hear_wind",
        "es": "Tú oyes el viento.",
        "pt": "Tu ouves o vento.",
        "tokens": ["you_sg", "hear", "def_art", "wind"],
    },
)


_validate()
