#!/usr/bin/env python3
"""What the 36 lects have, and lack, of the Bible's vocabulary.

For every word of the Latin Bible (`scripts/build_bible_lexicon.py`) a lect
"has a form" in one of two ways: Wiktionary lists a reflex of the Latin word
in that lect, or a dictionary entry of the lect is glossed with the Latin
word's first English gloss (for the French-glossed lects: with the Latin
word's French reflex). The report `docs/eval/bible_coverage.md` counts both
per lect and lists what is missing.

    python3 scripts/bible_coverage.py
"""

from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import audit_grid_sources as audit  # noqa: E402
import build_bible_lexicon as bible  # noqa: E402
import build_building_blocks as blocks  # noqa: E402
from vulgultra.romance_swadesh import LECT_NAMES, SOURCE_LANGS  # noqa: E402

REPORT = ROOT / "docs" / "eval" / "bible_coverage.md"
TOP = 1000


def gloss_key(gloss: str) -> str:
    """The first plain sense of a Latin entry's gloss: 'to say, talk' → 'say'."""
    first = re.split(r"[,;]", re.sub(r"\([^)]*\)|\[[^\]]*\]", " ", gloss))[0].strip().lower()
    return re.sub(r"^(to|a|an|the) ", "", first).strip(" .?!")


def glossed(lect: str) -> set[str]:
    """Every sense some dictionary entry of the lect is glossed with."""
    parts: set[str] = set()
    paths = [blocks.extract_of(lect), blocks.WORDS / f"kaikki-{blocks.EXTRACT.get(lect, lect)}.jsonl"]
    for path in dict.fromkeys(paths):
        if not path.is_file():
            continue
        with path.open(encoding="utf-8") as stream:
            for line in stream:
                for sense in json.loads(line).get("senses") or []:
                    for gloss in sense.get("glosses") or []:
                        parts |= audit.gloss_parts(gloss)
    return parts


def main() -> None:
    words, forms = bible.dictionary(), bible.inflected()
    counts, _, _ = bible.count_words(words, forms)
    ranked = counts.most_common()
    explained = sum(counts.values())
    key = {word: gloss_key(words[word]["gloss"]) for word, _ in ranked}
    french = {word: {form.lower() for form in words[word]["reflexes"].get("fr", [])} for word, _ in ranked}
    has: dict[str, dict[str, str]] = {}   # lect → word → "reflex" or "gloss"
    for lect in SOURCE_LANGS:
        senses = glossed(lect)
        in_french = blocks.gloss_language(lect) == "fr"
        found = {}
        for word, _ in ranked:
            if lect in words[word]["reflexes"]:
                found[word] = "reflex"
            elif (french[word] & senses) if in_french else (key[word] in senses):
                found[word] = "gloss"
        has[lect] = found
    lects_with = {word: sum(1 for lect in SOURCE_LANGS if word in has[lect]) for word, _ in ranked}
    top = [word for word, _ in ranked[:TOP]]
    lines = [
        "# What the lects have of the Bible's vocabulary", "",
        "Generated by `scripts/bible_coverage.py`. Do not edit by hand.", "",
        f"The Latin Bible has {len(ranked):,} distinct dictionary words "
        "([`bible_lexicon.md`](bible_lexicon.md)). A lect has a form for one of them if Wiktionary lists a "
        "**reflex** of the Latin word in that lect, or if a dictionary entry of the lect is **glossed** with "
        "the Latin word's first English sense (for a French-glossed lect: with the Latin word's French "
        "reflex). **Share of the text** weighs each word by how often the Bible uses it. The dictionaries on "
        "disk are what Wiktionary's editors have entered: a gap here is a gap in the data, and often not in "
        "the lect.", "",
        f"| lect | by reflex | by gloss only | words with a form | of {len(ranked):,} | of the {TOP:,} commonest | share of the text |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    order = sorted(SOURCE_LANGS, key=lambda lect: -len(has[lect]))
    for lect in order:
        found = has[lect]
        reflex = sum(1 for how in found.values() if how == "reflex")
        text_share = 100 * sum(counts[word] for word in found) / explained
        lines.append(f"| {LECT_NAMES.get(lect, lect)} ({lect}) | {reflex:,} | {len(found) - reflex:,} | {len(found):,} "
                     f"| {100 * len(found) // len(ranked)}% | {sum(1 for word in top if word in found)} | {text_share:.0f}% |")
    nowhere = [(word, n) for word, n in ranked if not lects_with[word]]
    thin = [(word, n) for word, n in ranked[:TOP] if 0 < lects_with[word] < 5]
    everywhere = sum(1 for word, _ in ranked if lects_with[word] >= 30)
    lines += [
        "", "## What is missing", "",
        f"- **In no lect at all:** {len(nowhere):,} of the {len(ranked):,} words, "
        f"{100 * sum(n for _, n in nowhere) / explained:.0f}% of the text. "
        f"Among the {TOP:,} commonest: {sum(1 for word, _ in nowhere if word in set(top))}.",
        f"- **In fewer than five lects**, among the {TOP:,} commonest: {len(thin)}.",
        f"- **In thirty lects or more:** {everywhere:,} words.", "",
        f"### The commonest words with a form in no lect", "",
        ", ".join(f"*{word}* ({n:,}; {key[word] or '?'})" for word, n in nowhere[:80]), "",
        f"### Among the {TOP:,} commonest, in fewer than five lects", "",
        ", ".join(f"*{word}* ({key[word] or '?'}; {lects_with[word]})" for word, _ in thin[:120]), "",
        f"### What each lect lacks among the {TOP:,} commonest", "",
        "The twelve commonest missing words per lect, with the sense looked for.", "",
        "| lect | missing | the commonest of them |", "|---|---:|---|",
    ]
    for lect in order:
        missing = [word for word in top if word not in has[lect]]
        lines.append(f"| {lect} | {len(missing)} | " + ", ".join(f"{word} ({key[word] or '?'})" for word in missing[:12]) + " |")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines[8:48]))
    print("\n".join(lines[48 + 0:56]))


if __name__ == "__main__":
    main()
